flowchart TD
    A[Java] -->History
    A -->B[How  Compiles i.e JVM,JKD]
    A -->C[OOPS concept]
    A -->D[Features]
   A -->E[String]
   A -->F[Keywords]
   A -->G[Program]
   B -->H[Convert machine code to byte code]
   C -->I[A]
   C -->J[p]
   C -->K[I]
   C -->L[E]
   C -->M[Class,obj,Methods]
   D -->N[Robust,Secure,Platform Independent etc]
   E -->O[Ways of creating]
   F -->P[this,that,super,final,]
   G -->Q[Car,BankAcoount,Cmd l args,Array,E Handling,Scanner class]
   A -->packages,Multithreading,ehandling
   A -->last(difference between )
   last -->Z[1.oop vs pop,2.Method vs constructor,3.error vs exception,]
   
   




